<?php

if (!defined('PUN'))
    exit;

/**
 * @copyright Copyright (c) 2015, Google Inc.
 * @link      https://www.google.com/recaptcha
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
require("include/google/appengine-https.php");

// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once("include/google/autoload.php");

// Register API keys at https://www.google.com/recaptcha/admin
$secret = '';

// Copy the config.php.dist file to config.php and update it with your keys to run the examples
if ($secret == '' && is_readable(__DIR__ . '/config_recaptcha.php')) {
    $config = include __DIR__ . '/config_recaptcha.php';
    $secret = $v2_config['secret'];
}

session_start();

// Effectively we're providing an API endpoint here that will accept the token, verify it, and return the action / score to the page
// In production, always sanitize and validate the input you retrieve from the request.
if (isset($_POST['form_sent']))
{
    if (isset($_POST['g-recaptcha-response']))
    {
        try
        {
             $recaptcha = new \ReCaptcha\ReCaptcha($secret);
             $gRecaptchaResponse = $_POST['g-recaptcha-response'];
             $resp = $recaptcha->verify($gRecaptchaResponse, $_SERVER['REMOTE_ADDR']);
             if ($resp->isSuccess()) {
                 // Verified!
             } else
             {
                 $errors = $resp->getErrorCodes();
//               print_r ($errors);
                 message($lang_register['Text mismatch']);
             }
        } catch (Exception $e) {
             // echo 'Caught exception: ',  $e->getMessage(), "\n";
	     message($lang_register['Text mismatch']);
        }
    } else message($lang_register['Text mismatch']);
}
?>
